import { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  // Ofertas da Semana 🔥 (4)
  {
    id: '1',
    name: 'Dipirona Monoidratada 500mg - 10 Comprimidos',
    ean: '7891000001011',
    sku: 'MED-DIP-001',
    manufacturer: 'Medley',
    category: 'Ofertas da Semana 🔥',
    price: 12.50,
    promoPrice: 8.90,
    stock: 500,
    images: ['https://picsum.photos/seed/dipirona/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Analgésico e antitérmico de rápida ação.',
  },
  {
    id: '2',
    name: 'Shampoo L\'Oréal Paris Elseve Hidra Hialurônico 400ml',
    ean: '7891000001028',
    sku: 'COSM-SHA-001',
    manufacturer: 'L\'Oréal',
    category: 'Ofertas da Semana 🔥',
    price: 34.90,
    promoPrice: 24.90,
    stock: 120,
    images: ['https://picsum.photos/seed/shampoo-hidra/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Preenche e retém a hidratação profunda na fibra capilar.',
  },
  {
    id: '3',
    name: 'Protetor Solar La Roche-Posay Anthelios Airlicium FPS 70',
    ean: '7891000001035',
    sku: 'COSM-SUN-001',
    manufacturer: 'La Roche-Posay',
    category: 'Ofertas da Semana 🔥',
    price: 99.00,
    promoPrice: 79.90,
    stock: 45,
    images: ['https://picsum.photos/seed/anthelios/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Alta proteção solar com controle inteligente de oleosidade.',
  },
  {
    id: '4',
    name: 'Fralda Pampers Confort Sec G - 60 Unidades',
    ean: '7891000001042',
    sku: 'BEBE-FRA-001',
    manufacturer: 'P&G',
    category: 'Ofertas da Semana 🔥',
    price: 89.90,
    promoPrice: 69.90,
    stock: 80,
    images: ['https://picsum.photos/seed/pampers/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Até 12 horas de sono sequinho para o seu bebê.',
  },

  // Medicamentos (4)
  {
    id: '5',
    name: 'Dorflex - 36 Comprimidos',
    ean: '7891000002018',
    sku: 'MED-DOR-001',
    manufacturer: 'Sanofi',
    category: 'Medicamentos',
    price: 28.50,
    stock: 300,
    images: ['https://picsum.photos/seed/dorflex/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Analgésico e relaxante muscular para dores corporais.',
  },
  {
    id: '6',
    name: 'Neosaldina - 30 Drágeas',
    ean: '7891000002025',
    sku: 'MED-NEO-001',
    manufacturer: 'Takeda',
    category: 'Medicamentos',
    price: 39.90,
    stock: 250,
    images: ['https://picsum.photos/seed/neosaldina/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Eficaz contra dores de cabeça e enxaquecas.',
  },
  {
    id: '7',
    name: 'Amoxicilina 500mg - 21 Cápsulas (Genérico)',
    ean: '7891000002032',
    sku: 'MED-AMO-001',
    manufacturer: 'Eurofarma',
    category: 'Medicamentos',
    price: 45.00,
    stock: 100,
    images: ['https://picsum.photos/seed/amoxicilina/400/400'],
    requiresPrescription: true,
    stripeType: 'Red',
    description: 'Antibiótico indicado para o tratamento de infecções bacterianas.',
  },
  {
    id: '8',
    name: 'Buscopan Composto - 20 Comprimidos',
    ean: '7891000002049',
    sku: 'MED-BUS-001',
    manufacturer: 'Boehringer Ingelheim',
    category: 'Medicamentos',
    price: 22.90,
    stock: 180,
    images: ['https://picsum.photos/seed/buscopan/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Alívio rápido de dores e cólicas abdominais.',
  },

  // Higiene Pessoal (2)
  {
    id: '9',
    name: 'Sabonete Dove Original 90g',
    ean: '7891000003015',
    sku: 'HIG-DOV-001',
    manufacturer: 'Unilever',
    category: 'Higiene Pessoal',
    price: 4.50,
    stock: 1000,
    images: ['https://picsum.photos/seed/dove/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Contém 1/4 de creme hidratante para pele macia.',
  },
  {
    id: '10',
    name: 'Creme Dental Colgate Total 12 90g',
    ean: '7891000003022',
    sku: 'HIG-COL-001',
    manufacturer: 'Colgate',
    category: 'Higiene Pessoal',
    price: 12.90,
    stock: 600,
    images: ['https://picsum.photos/seed/colgate/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Saúde bucal completa por até 12 horas.',
  },

  // Cosméticos e Beleza (2)
  {
    id: '11',
    name: 'Água Micelar L\'Oréal Paris 200ml',
    ean: '7891000004012',
    sku: 'COSM-MIC-001',
    manufacturer: 'L\'Oréal',
    category: 'Cosméticos e Beleza',
    price: 29.90,
    stock: 150,
    images: ['https://picsum.photos/seed/micelar/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Limpa, demaquila, purifica, suaviza e reequilibra.',
  },
  {
    id: '12',
    name: 'Esmalte Risqué Cremoso - Renda',
    ean: '7891000004029',
    sku: 'COSM-ESM-001',
    manufacturer: 'Risqué',
    category: 'Cosméticos e Beleza',
    price: 5.90,
    stock: 400,
    images: ['https://picsum.photos/seed/risque/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Hipoalergênico e com secagem rápida.',
  },

  // Mamãe & Bebê (2)
  {
    id: '13',
    name: 'Pomada Hipoglós Amêndoas 40g',
    ean: '7891000005019',
    sku: 'BEBE-HIP-001',
    manufacturer: 'Johnson & Johnson',
    category: 'Mamãe & Bebê',
    price: 19.90,
    stock: 200,
    images: ['https://picsum.photos/seed/hipoglos/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Protege contra assaduras com cheirinho suave.',
  },
  {
    id: '14',
    name: 'Lenços Umedecidos Huggies Tripla Proteção - 96 Unid',
    ean: '7891000005026',
    sku: 'BEBE-LEN-001',
    manufacturer: 'Kimberly-Clark',
    category: 'Mamãe & Bebê',
    price: 18.90,
    stock: 350,
    images: ['https://picsum.photos/seed/huggies/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Limpeza suave e segura para a pele do bebê.',
  },

  // Suplementos (2)
  {
    id: '15',
    name: 'Creatina Monohidratada Max Titanium 300g',
    ean: '7891000006016',
    sku: 'SUP-CRE-001',
    manufacturer: 'Max Titanium',
    category: 'Suplementos',
    price: 119.90,
    stock: 90,
    images: ['https://picsum.photos/seed/creatina/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Auxilia no aumento do desempenho físico durante exercícios.',
  },
  {
    id: '16',
    name: 'Centrum Multivitamínico Homem - 60 Cápsulas',
    ean: '7891000006023',
    sku: 'SUP-CEN-001',
    manufacturer: 'GSK',
    category: 'Suplementos',
    price: 89.00,
    stock: 110,
    images: ['https://picsum.photos/seed/centrum/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Energia, imunidade e saúde muscular para homens.',
  },

  // Ortopédicos (2)
  {
    id: '17',
    name: 'Tornozeleira Elástica Tensor - Tamanho M',
    ean: '7891000007013',
    sku: 'ORT-TOR-001',
    manufacturer: 'Tensor',
    category: 'Ortopédicos',
    price: 35.90,
    stock: 60,
    images: ['https://picsum.photos/seed/tornozeleira/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Proporciona suporte e compressão ao tornozelo.',
  },
  {
    id: '18',
    name: 'Joelheira Articulada Take Care',
    ean: '7891000007020',
    sku: 'ORT-JOE-001',
    manufacturer: 'Take Care',
    category: 'Ortopédicos',
    price: 125.00,
    stock: 30,
    images: ['https://picsum.photos/seed/joelheira/400/400'],
    requiresPrescription: false,
    stripeType: 'None',
    description: 'Estabilidade extra para o joelho em recuperação.',
  },
  {
    id: '19',
    name: '100% Whey Protein - 900g Max Titanium',
    ean: '7891000006030',
    sku: 'SUP-WHE-001',
    manufacturer: 'Max Titanium',
    category: 'Suplementos',
    price: 159.90,
    stock: 200,
    images: ['https://images.tcdn.com.br/img/img_prod/631481/100_whey_900g_max_titanium_533_1_20191217112028.jpg'],
    requiresPrescription: false,
    stripeType: 'None',
    description: '100% Whey Protein é um suplemento a base de proteína concentrada do soro do leite.',
    variations: [
      {
        name: 'Sabor',
        options: [
          { name: 'Baunilha', stock: 50 },
          { name: 'Chocolate', stock: 30 },
          { name: 'Coco', stock: 0 },
          { name: 'Morango', stock: 20 }
        ]
      },
      {
        name: 'Tamanho',
        options: [
          { name: '900g', stock: 100 }
        ]
      },
      {
        name: 'Embalagem',
        options: [
          { name: '1 Un', stock: 100 }
        ]
      }
    ]
  },
];
